{
  "Header": {
    "Original": "CVE-2020-36244 (The daemon in GENIVI diagnostic log and trace (DLT), is vulnerable to  ...)",
    "Line": 115254,
    "ID": "CVE-2020-36244",
    "Description": "(The daemon in GENIVI diagnostic log and trace (DLT), is vulnerable to  ...)"
  },
  "Annotations": [
    {
      "Original": "- dlt-daemon 2.18.6-1",
      "Line": 115255,
      "Type": "package",
      "Package": "dlt-daemon",
      "Kind": "fixed",
      "Version": "2.18.6-1"
    },
    {
      "Original": "[buster] - dlt-daemon \u003cno-dsa\u003e (Minor issue)",
      "Line": 115256,
      "Type": "package",
      "Release": "buster",
      "Package": "dlt-daemon",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/GENIVI/dlt-daemon/issues/265",
      "Line": 115257,
      "Type": "NOTE",
      "Description": "https://github.com/GENIVI/dlt-daemon/issues/265"
    },
    {
      "Original": "NOTE: https://github.com/GENIVI/dlt-daemon/pull/269",
      "Line": 115258,
      "Type": "NOTE",
      "Description": "https://github.com/GENIVI/dlt-daemon/pull/269"
    },
    {
      "Original": "NOTE: https://github.com/GENIVI/dlt-daemon/commit/af734fe097ed379b0aa5fcf551886b1ce5098052 (v2.18.6)",
      "Line": 115259,
      "Type": "NOTE",
      "Description": "https://github.com/GENIVI/dlt-daemon/commit/af734fe097ed379b0aa5fcf551886b1ce5098052 (v2.18.6)"
    }
  ]
}