{
  "Header": {
    "Original": "CVE-2021-4209 (A NULL pointer dereference flaw was found in GnuTLS. As Nettle's hash  ...)",
    "Line": 55251,
    "ID": "CVE-2021-4209",
    "Description": "(A NULL pointer dereference flaw was found in GnuTLS. As Nettle's hash  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3070-1}",
      "Line": 55252,
      "Type": "xref",
      "Bugs": [
        "DLA-3070-1"
      ]
    },
    {
      "Original": "- gnutls28 3.7.3-2",
      "Line": 55253,
      "Type": "package",
      "Package": "gnutls28",
      "Kind": "fixed",
      "Version": "3.7.3-2"
    },
    {
      "Original": "[bullseye] - gnutls28 3.7.1-5+deb11u1",
      "Line": 55254,
      "Type": "package",
      "Release": "bullseye",
      "Package": "gnutls28",
      "Kind": "fixed",
      "Version": "3.7.1-5+deb11u1"
    },
    {
      "Original": "[stretch] - gnutls28 \u003cpostponed\u003e (Minor issue)",
      "Line": 55255,
      "Type": "package",
      "Release": "stretch",
      "Package": "gnutls28",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2044156",
      "Line": 55256,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2044156"
    },
    {
      "Original": "NOTE: https://gitlab.com/gnutls/gnutls/-/issues/1306",
      "Line": 55257,
      "Type": "NOTE",
      "Description": "https://gitlab.com/gnutls/gnutls/-/issues/1306"
    },
    {
      "Original": "NOTE: https://gitlab.com/gnutls/gnutls/-/merge_requests/1503",
      "Line": 55258,
      "Type": "NOTE",
      "Description": "https://gitlab.com/gnutls/gnutls/-/merge_requests/1503"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.com/gnutls/gnutls/-/commit/3db352734472d851318944db13be73da61300568 (3.7.3)",
      "Line": 55259,
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.com/gnutls/gnutls/-/commit/3db352734472d851318944db13be73da61300568 (3.7.3)"
    }
  ]
}