{
  "Header": {
    "Original": "CVE-2022-3638 (A vulnerability was found in Nginx and classified as problematic. This ...)",
    "Line": 497,
    "ID": "CVE-2022-3638",
    "Description": "(A vulnerability was found in Nginx and classified as problematic. This ...)"
  },
  "Annotations": [
    {
      "Original": "- nginx \u003cnot-affected\u003e (Vulnerable code not present)",
      "Line": 498,
      "Type": "package",
      "Package": "nginx",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present"
    },
    {
      "Original": "NOTE: http://hg.nginx.org/nginx/rev/0422365794f7",
      "Line": 499,
      "Type": "NOTE",
      "Description": "http://hg.nginx.org/nginx/rev/0422365794f7"
    },
    {
      "Original": "NOTE: Introduced by: https://github.com/nginx/nginx/commit/5178da4f94fbae1daec2800bc7fd74cd2923c5bd (release-1.23.1)",
      "Line": 500,
      "Type": "NOTE",
      "Description": "Introduced by: https://github.com/nginx/nginx/commit/5178da4f94fbae1daec2800bc7fd74cd2923c5bd (release-1.23.1)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/nginx/nginx/commit/14341ce2377d38a268261e0fec65b6915ae6e95e (release-1.23.1)",
      "Line": 501,
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/nginx/nginx/commit/14341ce2377d38a268261e0fec65b6915ae6e95e (release-1.23.1)"
    }
  ]
}