{
  "Header": {
    "Original": "CVE-2022-3169 (A flaw was found in the Linux kernel. A denial of service flaw may occ ...)",
    "Line": 7795,
    "ID": "CVE-2022-3169",
    "Description": "(A flaw was found in the Linux kernel. A denial of service flaw may occ ...)"
  },
  "Annotations": [
    {
      "Original": "- linux \u003cunfixed\u003e",
      "Line": 7796,
      "Type": "package",
      "Package": "linux",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2125341",
      "Line": 7797,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2125341"
    },
    {
      "Original": "NOTE: https://bugzilla.kernel.org/show_bug.cgi?id=214771",
      "Line": 7798,
      "Type": "NOTE",
      "Description": "https://bugzilla.kernel.org/show_bug.cgi?id=214771"
    }
  ]
}