{
  "Header": {
    "Original": "CVE-2020-25600 (An issue was discovered in Xen through 4.14.x. Out of bounds event cha ...)",
    "Line": 150659,
    "ID": "CVE-2020-25600",
    "Description": "(An issue was discovered in Xen through 4.14.x. Out of bounds event cha ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4769-1}",
      "Line": 150660,
      "Type": "xref",
      "Bugs": [
        "DSA-4769-1"
      ]
    },
    {
      "Original": "- xen 4.14.0+80-gd101b417b7-1",
      "Line": 150661,
      "Type": "package",
      "Package": "xen",
      "Kind": "fixed",
      "Version": "4.14.0+80-gd101b417b7-1"
    },
    {
      "Original": "[stretch] - xen \u003cend-of-life\u003e (DSA 4602-1)",
      "Line": 150662,
      "Type": "package",
      "Release": "stretch",
      "Package": "xen",
      "Kind": "end-of-life",
      "Description": "DSA 4602-1"
    },
    {
      "Original": "NOTE: https://xenbits.xen.org/xsa/advisory-342.html",
      "Line": 150663,
      "Type": "NOTE",
      "Description": "https://xenbits.xen.org/xsa/advisory-342.html"
    }
  ]
}