{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@gitlab.com",
      "ID": "CVE-2022-3627"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "LibTIFF 4.4.0 has an out-of-bounds write in _TIFFmemcpy in libtiff/tif_unix.c:346 when called from extractImageSection, tools/tiffcrop.c:6860, allowing attackers to cause a denial-of-service via a crafted tiff file. For users that compile libtiff from sources, the fix is available with commit 236b7191."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://gitlab.com/libtiff/libtiff/-/commit/236b7191f04c60d09ee836ae13b50f812c841047",
          "refsource": "MISC",
          "tags": [],
          "url": "https://gitlab.com/libtiff/libtiff/-/commit/236b7191f04c60d09ee836ae13b50f812c841047"
        },
        {
          "name": "https://gitlab.com/libtiff/libtiff/-/issues/411",
          "refsource": "MISC",
          "tags": [],
          "url": "https://gitlab.com/libtiff/libtiff/-/issues/411"
        },
        {
          "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-3627.json",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-3627.json"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2022-10-21T16:42Z",
  "publishedDate": "2022-10-21T16:15Z"
}