{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "libxml2",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "libxml2",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "libxml2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "libxml2",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat JBoss Core Services",
      "fix_state": "Under investigation",
      "package_name": "libxml2",
      "cpe": "cpe:/a:redhat:jboss_core_services:1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2022-10-14T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2022-40304 libxml2: dict corruption caused by entity reference cycles",
    "id": "2136288",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2136288"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "8.2",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-415",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-40304",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}